Steps after If should run when Schedule step is still Pending
danielgerlag/workflow-core pull request #605
Opened 2020-07-20 15:04 UTC by andre-pt

first of all, I'm not a .NET guy :)

we have been using jworkflow for a while now and recently a new use-case came up which in our opinion it's not the correct behaviour.

Consider the following workflow:
```
            builder
                .StartWith(context =>
                {
                    Console.WriteLine("STEP1");
                    return ExecutionResult.Next();
                })
                .Schedule(data => TimeSpan.FromSeconds(10)).Do(schedule => schedule
                    .StartWith(context => Console.WriteLine("STEP3"))
                )
                .If(data => 1 == 1).Do(then => then
                    .StartWith(context =>
                    {
                        Console.WriteLine("STEP2");
                        return ExecutionResult.Next();
                    })
                    .Then(Context =>
                    {
                        Console.WriteLine("STEP4");
                        return ExecutionResult.Next();
                    })
                )
                .Then(context =>
                {
                    Console.WriteLine("STEP5");
                    return ExecutionResult.Next();
                });
```

Our expected output would be:
```
STEP1
STEP2
STEP4
STEP5
STEP3
```

but it was actually
```
STEP1
STEP2
STEP4
STEP3
STEP5
```

During our investigation, we figured steps added after the If branch were never executed until the Schedule step was completed, so we have adapted the logic of `WorkflowCore.Services.WorkflowExecutor.DetermineNextExecutionTime`.

Is this a correct assumption or did we interpret the use case in a different way?

Thanks in advance.
Andre and @poberbichler

2020-11-01 05:30 UTC, andre-pt commented
hi @danielgerlag 
did you have an opportunity to look into this topic?

thanks
André

2020-11-01 20:41 UTC, danielgerlag commented
@andre-pt sorry this one slipped under my radar... I will try spend some time debugging & understanding the issue this week.

2020-11-07 16:28 UTC, danielgerlag requested changes

2020-11-07 16:28 UTC, danielgerlag commented on src/WorkflowCore/Services/WorkflowExecutor.cs
> -            if (workflow.NextExecution == null)
I think the only required change is to remove this `if` statement and always execute the inner code.
We can remove all the other changes... seems like an attempt for optimization that is causing a problem.

2020-11-15 16:28 UTC, danielgerlag commented on src/WorkflowCore/Services/WorkflowExecutor.cs
> -            if (workflow.NextExecution == null)
@andre-pt this is a valid bug that needs to be fixed.  Do you want to do it with this PR or should I open a separate one?

2020-11-21 16:11 UTC, danielgerlag commented on src/WorkflowCore/Services/WorkflowExecutor.cs
> -            if (workflow.NextExecution == null)
https://github.com/danielgerlag/workflow-core/pull/700

2025-06-01 16:35 UTC, closed without merging